### ISSUE TITLE
support for Jekyll 3.0 and newer

### ISSUE THREAD

**Issue by xxmatxx** [karloespiritu/BlackDoc#3]
i have this error and because i am beginner with Jekyll i dont how repair it. 

> Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check http://jekyllrb.com/docs/upgrading/ for more info.

**Comment by karloespiritu** [comment]
Jekyll 3.X and newer is now supported in the latest version. Thanks.
