### ISSUE TITLE
Can't get it work on local

### ISSUE THREAD

**Issue by FacundoAcevedo** [karloespiritu/BlackDoc#4]
Hi, I'm getting this error
`bundle exec jekyll serve
Configuration file: /home/facu/proyectos/mysite/_config.yml
            Source: /home/facu/proyectos/mysite
       Destination: /home/facu/proyectos/mysite/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.`

I've done `bundle install`, and everything have installed OK.

I've added this line to **_config.yml**:

`repository:           https://github.com/FacundoAcevedo/FacundoAcevedo.github.io.git`

but then, the next error shows:

`bundle exec jekyll serve
Configuration file: /home/facu/proyectos/mysite/_config.yml
            Source: /home/facu/proyectos/mysite
       Destination: /home/facu/proyectos/mysite/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
jekyll 3.1.6 | Error:  Invalid Repository. Use user/repo format.
`

I've created a Token, so then I run:
`JEKYLL_GITHUB_TOKEN=abc123def456 bundle exec jekyll serve`

But fails and show:
`JEKYLL_GITHUB_TOKEN=abc123def456 bundle exec jekyll serve
`Configuration file: /home/facu/proyectos/mysite/_config.yml
            Source: /home/facu/proyectos/mysite
       Destination: /home/facu/proyectos/mysite/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.1.6 | Error:  Invalid Repository. Use user/repo format.

**Comment by mvmohitverma54** [comment]
it is not working because access token code is ssh generated and this repo should add all of us for access or it wont work

**Comment by karloespiritu** [comment]
Github repo in `config.yml` should be in the ff format: 

```
 github:
  repo:           https://github.com/<username>/<reponame>
```
